[project]
name = "taxi-fare-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "numpy>=1.26.0",
    "scikit-learn>=1.9.1",
    "matplotlib>=3.9.3",
    "seaborn>=0.13.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.4",
]

[project.scripts]
pull_trip_data = "scripts.pull_trip_data:main"

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "scripts"
module-root = ""
